import "./globals.css";

export const metadata = {
  title: "캐릭터 숙제 관리",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}